### ISSUE TITLE
PCB options for PCBWay order?

### ISSUE THREAD

**Issue by mczero80** [dabonetn/Swift-Internal#1]
Hi,

I have a question, which pcb size is correct for PCBWay and which other order options do you recommend?

Thank you!

**Comment by dabonetn** [comment]
Since it's not a cartridge, just the standard thickness is fine. It's just a basic PCB.
No need for gold, or any other add ons.
Also look at Jlcpcb, they are really cheap also.

**Comment by mczero80** [comment]
Ahh cool didn't now that manufacturer.

Good project, I am curious how it will turn out, especially the C128 version :)
